name: Docker Build & Push Nilliond (main)
# Build & Push builds the simapp docker image on every push to main and
# and pushes the image to https://ghcr.io/cosmos/ibc-go-simd
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nilliond 

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
      with:
        images: ${{ env.REGISTRY }}/NillionNetwork/${{ env.IMAGE_NAME }}

    - name: Build Docker image
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}

    - name: Test nilliond is runnable
      run: |
        docker run --rm ${{ steps.meta.outputs.tags }}
    - name: Log in to the Container registry
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
